server:
  port: 8666

spring:
  application:
    name: ${APP_NAME}

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=${DB_SCHEMA}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:validate}
    show-sql: ${SHOW_SQL:true}

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS:health,info,metrics}
  endpoint:
    health:
      show-details: ${HEALTH_DETAILS:always}

logging:
  level:
    com.mgnetworking: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}

# Configurations spécifiques à l'API
app:
  keycloak:
    url: ${KEYCLOAK_URL:http://localhost:8080}
  storage:
    uploads-path: ${UPLOADS_PATH:/tmp/uploads}